<?php
return [
    'comments' => [
        'enabled' => true,
        'title' => 'Comment Plugin',
        'description' => 'Plugin for comment system',
        'author' => 'Your Name',
        'version' => '1.0',
        'settings' => [
            'enable' => true,
            'enable_posttype' => [
                'posts',
                'stories',
                'chapters',
                'articles',
            ],
            'enable_emoji' => true,
            'enable_like' => true,
            'enable_reply' => true,
            'enable_report' => true,
            'enable_notify' => true,
            'enable_notify_email' => true,
            'enable_moderation' => true,
            'moderation_roles' => ['admin', 'editor', 'moderator'],
            'custom_css' => '',
            'custom_js' => '',
            'permissions' => [
                'can_comment' => ['user', 'admin', 'editor', 'moderator'],
                'can_delete' => ['admin', 'moderator'],
                'can_edit' => ['admin', 'moderator'],
            ],
            'api_enabled' => true,
            'api_keys' => [],
            'theme' => 'light',
            'language' => 'vi',
            'setting_level' => [
                'level' => 1,
                'level_mobile' => 1,
            ],
            'setting_sort'  => [
                'sortby' => 'created_at',
                'sort' => 'DESC',
            ],
            'setting_perpage' => [
                'perpage' => 10,
                'perpage_mobile' => 5,
            ],
        ],
    ],
    'shopping' => [
        'enabled' => true,
        'title' => 'Shopping Plugin',
        'description' => 'Plugin for shopping system',
        'author' => 'Your Name',
        'version' => '1.0',
        'settings' => [
            'enable' => true,
            'permissions' => [
                'order_view' => ['admin', 'editor', 'moderator'],
                'order_add' => ['admin', 'editor', 'moderator'],
                'order_edit' => ['admin', 'moderator'],
                'order_delete' => ['admin', 'moderator'],
                'product_view' => ['admin', 'editor', 'moderator'],
                'product_add' => ['admin', 'editor', 'moderator'],
                'product_edit' => ['admin', 'editor', 'moderator'],
                'product_delete' => ['admin', 'editor', 'moderator'],
                'customer_view' => ['admin', 'editor', 'moderator'],
                'customer_add' => ['admin', 'moderator'],
                'customer_edit' => ['admin', 'moderator'],
                'customer_delete' => ['admin', 'moderator'],
                'coupon_view' => ['admin', 'editor', 'moderator'],
                'coupon_add' => ['admin', 'editor', 'moderator'],
                'coupon_edit' => ['admin', 'editor', 'moderator'],
                'coupon_delete' => ['admin', 'editor', 'moderator'],
                'transaction_view' => ['admin', 'editor', 'moderator'],
                'transaction_add' => ['admin', 'moderator'],
                'transaction_edit' => ['admin', 'moderator'],
                'transaction_delete' => ['admin', 'moderator'],
                'shipping_view' => ['admin', 'editor', 'moderator'],
                'shipping_add' => ['admin', 'editor', 'moderator'],
                'shipping_edit' => ['admin', 'editor', 'moderator'],
                'shipping_delete' => ['admin', 'editor', 'moderator'],
                'taxes_view' => ['admin', 'editor', 'moderator'],
                'taxes_add' => ['admin', 'editor', 'moderator'],
                'taxes_edit' => ['admin', 'editor', 'moderator'],
                'taxes_delete' => ['admin', 'editor', 'moderator'],
            ],
            'enable_posttype' => [
                'shop',
                'products',
                'orders',
                'collections',
                'coupons',
                'customers',
                'transactions',
                'shipping',
                'taxes',
            ],
            'enable_reviews' => true,
            'enable_coupons' => true,
            //'enable_wishlist' => true,
            //'enable_compare' => false,
            'currency' => [
                'vi' => [
                    'symbol' => '₫',
                    'name' => 'VND',
                    'code' => 'VND',
                    'position' => 'left',
                ],
                'en' => [
                    'symbol' => '$',
                    'name' => 'USD',
                    'code' => 'USD',
                    'position' => 'left',
                ],
                'cn' => [
                    'symbol' => '¥',
                    'name' => 'CNY',
                    'code' => 'CNY',
                    'position' => 'left',
                ],
            ],
            'taxes' => [
                [
                    'name' => 'VAT',
                    'rate' => 10,
                    'type' => 'percentage',
                    'description' => 'VAT is a tax on the value added to goods and services at each stage of production or distribution.',
                    'enabled' => true,
                    'countries' => ['VN','TH','ID','JP','KR','PH','MY','SG'],
                ],
                [
                    'name' => 'VAT',
                    'rate' => 5,
                    'type' => 'percentage',
                    'description' => 'VAT is a tax on the value added to goods and services at each stage of production or distribution.',
                    'enabled' => true,
                    'countries' => ['US','CA','AU','NZ','GB','IE','FR','DE','IT','ES'],
                ],
                [
                    'name' => 'VAT',
                    'rate' => 12,
                    'type' => 'percentage',
                    'description' => 'VAT is a tax on the value added to goods and services at each stage of production or distribution.',
                    'enabled' => true,
                    'countries' => ['CN','HK','TW','MO'],
                ],
            ],
            'shippping' => [
                [
                    'name' => 'Standard Shipping',
                    'rate' => 5,
                    'type' => 'flat_rate',
                    'description' => 'Standard shipping is a method of shipping that is typically the most economical and takes the longest time to deliver.',
                    'enabled' => true,
                    'countries' => ['VN','TH','ID','JP','KR','PH','MY','SG'],
                ],
                [
                    'name' => 'Express Shipping',
                    'rate' => 10,
                    'type' => 'flat_rate',
                    'description' => 'Express shipping is a method of shipping that is typically the fastest and most expensive.',
                    'enabled' => true,
                    'countries' => ['US','CA','AU','NZ','GB','IE','FR','DE','IT','ES'],
                ],
                [
                    'name' => 'Free Shipping',
                    'rate' => 0,
                    'type' => 'flat_rate',
                    'description' => 'Free shipping is a method of shipping that does not charge the customer for shipping.',
                    'enabled' => true,
                    'countries' => ['CN','HK','TW','MO'],
                ],
                [
                    'name' => 'Shipping by Province',
                    'rate' => 0,
                    'type' => 'flat_rate',
                    'description' => 'Shipping by Province is a method of shipping that calculates rates based on the province of the sender and recipient.',
                    'enabled' => true,
                    'countries' => ['VN'],
                    'province' => [
                        'hanoi' => 10,
                        'hochiminh' => 20,
                        'danang' => 30,
                        'haiphong' => 40,
                        'cantho' => 50,
                    ],
                ],
            ],
            'payment'   =>  [
                'paypal' => [
                    'enabled' => true,
                    'client_id' => '',
                    'secret' => '',
                    'sandbox' => true,
                ],
                'stripe' => [
                    'enabled' => true,
                    'publishable_key' => '',
                    'secret_key' => '',
                    'webhook_secret' => '',
                ],
                'bank_transfer' => [
                    'enabled' => true,
                    'account_name' => '',
                    'account_number' => '',
                    'bank_name' => '',
                ],
            ],
            'business'  => [
                'name' => 'Your Business Name',
                'address' => 'Your Business Address',
                'phone' => 'Your Business Phone',
                'email' => 'Your Business Email',
                'website' => 'Your Business Website',
            ],
            
            'log_activity' => true,
            'api_enabled' => true,
            'api_keys' => [],
            'theme' => 'default',
            'language' => 'vi',
        ],
    ],
];