<?php

/**
 * User Roles Configuration
 * Generated by CMSFullForm Installer
 */

return [
    'admin' => [
        'name' => 'Administrator',
        'description' => 'Full access to all features and settings',
        'permissions' => [
            'Backend\\Home' => [
                'index',
            ],
            'Backend\\Files' => [
                'index',
                'add',
                'edit',
                'delete',
                'manage',
            ],
            'Backend\\Posts' => [
                'index',
                'edit',
                'add',
                'delete',
                'clone',
                'copy',
                'import',
            ],
            'Backend\\Users' => [
                'index',
                'edit',
                'add',
                'delete',
                'changestatus',
                'update_status',
            ],
            'Backend\\Options' => [
                'index',
                'add',
                'edit',
                'delete',
            ],
            'Backend\\Languages' => [
                'index',
                'add',
                'edit',
                'setdefault',
                'changestatus',
                'delete',
            ],
            'Backend\\Plugins' => [
                'index',
                'action',
                'upload',
                'uploadWithOverwrite',
            ],
            'Backend\\Themes' => [
                'index',
                'action',
                'upload',
                'uploadWithOverwrite',
            ],
        ],
        'is_active' => true,
        'created_at' => '2025-09-04 06:21:49',
    ],
    'moderator' => [
        'name' => 'Moderator',
        'description' => 'Manage content and moderate users',
        'permissions' => [
            'Backend\\Home' => [
                'index',
            ],
            'Backend\\Files' => [
                'index',
                'add',
                'edit',
                'delete',
                'manage',
            ],
            'Backend\\Posts' => [
                'index',
                'edit',
                'add',
                'delete',
                'clone',
                'copy',
                'import',
            ],
        ],
        'is_active' => true,
        'created_at' => '2025-09-04 06:21:49',
    ],
    'author' => [
        'name' => 'Author',
        'description' => 'Create and manage own content',
        'permissions' => [
            'Backend\\Home' => [
                'index',
            ],
            'Backend\\Files' => [
                'index',
                'add',
                'edit',
                'delete',
                'manage',
            ],
            'Backend\\Posts' => [
                'index',
                'edit',
                'add',
                'delete',
                'clone',
                'copy',
                'import',
            ],
        ],
        'is_active' => true,
        'created_at' => '2025-09-04 06:21:49',
    ],
    'member' => [
        'name' => 'Member',
        'description' => 'Basic access to view content',
        'permissions' => [
            'Backend\\Home' => [
                'index',
            ],
        ],
        'is_active' => true,
        'created_at' => '2025-09-04 06:21:49',
    ],
    'seller' => [
        'name' => 'Seller',
        'description' => 'Custom role',
        'permissions' => [
            'Backend\\Home' => [
                'index',
            ],
        ],
        'is_active' => true,
        'created_at' => '2025-09-04 06:21:49',
    ],
];
